version: '3.2'

services:
  logstash:
    build: ./logstash
    env_file:
      .env
    networks:
      - WeST-crawler
    volumes:
      - type: bind
        source: ./output
        target: /usr/share/logstash/output
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline/
    command: bin/logstash --config.reload.automatic

  web:
    build: ./python
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./logstash/pipeline
        target: /pipeline

networks:
  WeST-crawler:
